#name, main, version and api are required
name: TreeCutter
main: TreeCutter\TreeCutter
src-namespace-prefix: TreeCutter
version: 1.0.0
api: 4.0.0

load: POSTWORLD
author: Dca
description: This plugin helps players chop down trees more easily. When a player cuts down a log, the plugin will automatically chop down adjacent logs and leaves, saving the player a lot of time and effort.
website: https://github.com/dca/Minecraft-TreeCutter

